force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <label>Alert</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

alerts/force-app/main/default/objects/Alert__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Alerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alert_User_Option__c/Alert_User_Option__c.object-meta.xml
<CustomObject>
    <label>Alert User Option</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Alert User Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alert User Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Alert_User_Option__c/fields/Alert__c.field-meta.xml
<CustomField>
    <fullName>Alert__c</fullName>
    <label>Alert</label>
    <referenceTo>Alert__c</referenceTo>
    <relationshipLabel>Alert User Options</relationshipLabel>
    <relationshipName>Alert_User_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Alert_User_Option__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Alert_User_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AlertConsoleController.cls
/**
* @author davidbrowaeys[js]
* @date 01/11/2018
* @group Alert
* @description Controller for Alert Console Lightning Component. 
*/
public class AlertConsoleController {
    /**
    * @author davidbrowaeys[js]
    * @date 01/11/2018
    * @description This method return a list of alert base on a specified category and record id
    * @param category alert category
    * @param parentId id of the object record
    * @return list of alerts that meet the criteria
    */
    @AuraEnabled
    public static Alert__c[] getAlerts(String category, String recordId){
        return AlertService.getRecordAlerts(category, recordId);
    }
    /**
    * @author davidbrowaeys[js]
    * @date 01/11/2018
    * @description This method hide or delete an alert for the current user
    * @param alertId id of the alert to hide or delete
    */
    @AuraEnabled
    public static void hideUserAlert(String alertId){
        Alert__c alert = AlertService.getAlertById(alertId);
        if (alert.User__c == Userinfo.getUserId()){//the alert belong to the current user
            delete alert;
        }else if (alert.User__c == null){//the alert belong to business support
            insert new Alert_User_Option__c (Alert__c = alert.Id, User__c = Userinfo.getUserId());
        }else { //current user is not authorised to delete alerts. System admin or Business support should be able to delete alert from Alert tab
            throw new IllegalArgumentException('You are not authorize to perform this action.');
        }   
    }
}